apiVersion: apps/v1
kind: Deployment
metadata:
  name: item-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: item-service
  template:
    metadata:
      labels:
        app: item-service
    spec:
      containers:
        - name: item-service
          image: seungjusuh/item-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: JASYPT_PASSWORD
              value: "your-encryption-password"
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"